//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//
namespace RatCow.BACS.Formats.ADDACS
{
  using System.Xml.Serialization;

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class BACSDocument
  {
    private Data dataField;

    private string signatureMethodField;

    private byte[] signatureField;

    /// <remarks/>
    public Data Data
    {
      get
      {
        return this.dataField;
      }
      set
      {
        this.dataField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( DataType = "NCName" )]
    public string SignatureMethod
    {
      get
      {
        return this.signatureMethodField;
      }
      set
      {
        this.signatureMethodField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( DataType = "base64Binary" )]
    public byte[] Signature
    {
      get
      {
        return this.signatureField;
      }
      set
      {
        this.signatureField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class Data
  {
    private MessagingAdvices messagingAdvicesField;

    /// <remarks/>
    public MessagingAdvices MessagingAdvices
    {
      get
      {
        return this.messagingAdvicesField;
      }
      set
      {
        this.messagingAdvicesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class MessagingAdvices
  {
    private MessagingHeader messagingHeaderField;

    private AddresseeInformation addresseeInformationField;

    private MessagingAdvice[] messagingAdviceField;

    private MessagingError messagingErrorField;

    /// <remarks/>
    public MessagingHeader MessagingHeader
    {
      get
      {
        return this.messagingHeaderField;
      }
      set
      {
        this.messagingHeaderField = value;
      }
    }

    /// <remarks/>
    public AddresseeInformation AddresseeInformation
    {
      get
      {
        return this.addresseeInformationField;
      }
      set
      {
        this.addresseeInformationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( "MessagingAdvice" )]
    public MessagingAdvice[] MessagingAdvice
    {
      get
      {
        return this.messagingAdviceField;
      }
      set
      {
        this.messagingAdviceField = value;
      }
    }

    /// <remarks/>
    public MessagingError MessagingError
    {
      get
      {
        return this.messagingErrorField;
      }
      set
      {
        this.messagingErrorField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class MessagingHeader
  {
    private string advicetypeField;

    private string documentnumberField;

    private string envelopesequencenumberField;

    private string reportgenerationdateField;

    private string reporttypeField;

    private string streamidentifierField;

    private string subjectfirstaosnField;

    private string subjectlastaosnField;

    private string usernameField;

    private string usernumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "advice-type", DataType = "NCName" )]
    public string advicetype
    {
      get
      {
        return this.advicetypeField;
      }
      set
      {
        this.advicetypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "document-number", DataType = "integer" )]
    public string documentnumber
    {
      get
      {
        return this.documentnumberField;
      }
      set
      {
        this.documentnumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "envelope-sequence-number", DataType = "integer" )]
    public string envelopesequencenumber
    {
      get
      {
        return this.envelopesequencenumberField;
      }
      set
      {
        this.envelopesequencenumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "report-generation-date", DataType = "NMTOKEN" )]
    public string reportgenerationdate
    {
      get
      {
        return this.reportgenerationdateField;
      }
      set
      {
        this.reportgenerationdateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "report-type", DataType = "integer" )]
    public string reporttype
    {
      get
      {
        return this.reporttypeField;
      }
      set
      {
        this.reporttypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "stream-identifier", DataType = "integer" )]
    public string streamidentifier
    {
      get
      {
        return this.streamidentifierField;
      }
      set
      {
        this.streamidentifierField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "subject-first-aosn", DataType = "integer" )]
    public string subjectfirstaosn
    {
      get
      {
        return this.subjectfirstaosnField;
      }
      set
      {
        this.subjectfirstaosnField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "subject-last-aosn", DataType = "integer" )]
    public string subjectlastaosn
    {
      get
      {
        return this.subjectlastaosnField;
      }
      set
      {
        this.subjectlastaosnField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "user-name" )]
    public string username
    {
      get
      {
        return this.usernameField;
      }
      set
      {
        this.usernameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "user-number", DataType = "integer" )]
    public string usernumber
    {
      get
      {
        return this.usernumberField;
      }
      set
      {
        this.usernumberField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class AddresseeInformation
  {
    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class MessagingAdvice
  {
    private string aosnField;

    private string effectivedateField;

    private string payeraccountnumberField;

    private string payernameField;

    private string payernewaccountnumberField;

    private string payernewnameField;

    private string payernewsortcodeField;

    private string payersortcodeField;

    private string reasoncodeField;

    private string recordtypeField;

    private string referenceField;

    private string usernumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string aosn
    {
      get
      {
        return this.aosnField;
      }
      set
      {
        this.aosnField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "effective-date", DataType = "NMTOKEN" )]
    public string effectivedate
    {
      get
      {
        return this.effectivedateField;
      }
      set
      {
        this.effectivedateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-account-number", DataType = "integer" )]
    public string payeraccountnumber
    {
      get
      {
        return this.payeraccountnumberField;
      }
      set
      {
        this.payeraccountnumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-name" )]
    public string payername
    {
      get
      {
        return this.payernameField;
      }
      set
      {
        this.payernameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-new-account-number", DataType = "integer" )]
    public string payernewaccountnumber
    {
      get
      {
        return this.payernewaccountnumberField;
      }
      set
      {
        this.payernewaccountnumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-new-name" )]
    public string payernewname
    {
      get
      {
        return this.payernewnameField;
      }
      set
      {
        this.payernewnameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-new-sort-code", DataType = "integer" )]
    public string payernewsortcode
    {
      get
      {
        return this.payernewsortcodeField;
      }
      set
      {
        this.payernewsortcodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "payer-sort-code", DataType = "integer" )]
    public string payersortcode
    {
      get
      {
        return this.payersortcodeField;
      }
      set
      {
        this.payersortcodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "reason-code", DataType = "integer" )]
    public string reasoncode
    {
      get
      {
        return this.reasoncodeField;
      }
      set
      {
        this.reasoncodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "record-type", DataType = "NCName" )]
    public string recordtype
    {
      get
      {
        return this.recordtypeField;
      }
      set
      {
        this.recordtypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string reference
    {
      get
      {
        return this.referenceField;
      }
      set
      {
        this.referenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( "user-number", DataType = "integer" )]
    public string usernumber
    {
      get
      {
        return this.usernumberField;
      }
      set
      {
        this.usernumberField = value;
      }
    }

    [XmlIgnore]
    public string FileReference { get; set; }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class MessagingError
  {
  }
}