//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//
namespace RatCow.BACS.Formats.ARUDD
{
  using System.Xml.Serialization;

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class BACSDocument
  {
    private Data dataField;

    private string signatureMethodField;

    private byte[] signatureField;

    /// <remarks/>
    public Data Data
    {
      get
      {
        return this.dataField;
      }
      set
      {
        this.dataField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( DataType = "NCName" )]
    public string SignatureMethod
    {
      get
      {
        return this.signatureMethodField;
      }
      set
      {
        this.signatureMethodField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( DataType = "base64Binary" )]
    public byte[] Signature
    {
      get
      {
        return this.signatureField;
      }
      set
      {
        this.signatureField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class Data
  {
    private ARUDD aRUDDField;

    /// <remarks/>
    public ARUDD ARUDD
    {
      get
      {
        return this.aRUDDField;
      }
      set
      {
        this.aRUDDField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class ARUDD
  {
    private Header headerField;

    private AddresseeInformation addresseeInformationField;

    private ServiceLicenseInformation serviceLicenseInformationField;

    private Advice adviceField;

    /// <remarks/>
    public Header Header
    {
      get
      {
        return this.headerField;
      }
      set
      {
        this.headerField = value;
      }
    }

    /// <remarks/>
    public AddresseeInformation AddresseeInformation
    {
      get
      {
        return this.addresseeInformationField;
      }
      set
      {
        this.addresseeInformationField = value;
      }
    }

    /// <remarks/>
    public ServiceLicenseInformation ServiceLicenseInformation
    {
      get
      {
        return this.serviceLicenseInformationField;
      }
      set
      {
        this.serviceLicenseInformationField = value;
      }
    }

    /// <remarks/>
    public Advice Advice
    {
      get
      {
        return this.adviceField;
      }
      set
      {
        this.adviceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class Header
  {
    private string adviceNumberField;

    private string currentProcessingDateField;

    private string reportTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string adviceNumber
    {
      get
      {
        return this.adviceNumberField;
      }
      set
      {
        this.adviceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NMTOKEN" )]
    public string currentProcessingDate
    {
      get
      {
        return this.currentProcessingDateField;
      }
      set
      {
        this.currentProcessingDateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string reportType
    {
      get
      {
        return this.reportTypeField;
      }
      set
      {
        this.reportTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class AddresseeInformation
  {
    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class ServiceLicenseInformation
  {
    private string userNameField;

    private string userNumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userName
    {
      get
      {
        return this.userNameField;
      }
      set
      {
        this.userNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string userNumber
    {
      get
      {
        return this.userNumberField;
      }
      set
      {
        this.userNumberField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class Advice
  {
    private OriginatingAccountRecords originatingAccountRecordsField;

    /// <remarks/>
    public OriginatingAccountRecords OriginatingAccountRecords
    {
      get
      {
        return this.originatingAccountRecordsField;
      }
      set
      {
        this.originatingAccountRecordsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class OriginatingAccountRecords
  {
    private OriginatingAccountRecord originatingAccountRecordField;

    /// <remarks/>
    public OriginatingAccountRecord OriginatingAccountRecord
    {
      get
      {
        return this.originatingAccountRecordField;
      }
      set
      {
        this.originatingAccountRecordField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class OriginatingAccountRecord
  {
    private OriginatingAccount originatingAccountField;

    private ReturnedDebitItem[] returnedDebitItemField;

    private Totals totalsField;

    /// <remarks/>
    public OriginatingAccount OriginatingAccount
    {
      get
      {
        return this.originatingAccountField;
      }
      set
      {
        this.originatingAccountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute( "ReturnedDebitItem" )]
    public ReturnedDebitItem[] ReturnedDebitItem
    {
      get
      {
        return this.returnedDebitItemField;
      }
      set
      {
        this.returnedDebitItemField = value;
      }
    }

    /// <remarks/>
    public Totals Totals
    {
      get
      {
        return this.totalsField;
      }
      set
      {
        this.totalsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class OriginatingAccount
  {
    private string bankNameField;

    private string branchNameField;

    private string nameField;

    private string numberField;

    private string sortCodeField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bankName
    {
      get
      {
        return this.bankNameField;
      }
      set
      {
        this.bankNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string branchName
    {
      get
      {
        return this.branchNameField;
      }
      set
      {
        this.branchNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NMTOKEN" )]
    public string sortCode
    {
      get
      {
        return this.sortCodeField;
      }
      set
      {
        this.sortCodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class ReturnedDebitItem
  {
    private PayerAccount payerAccountField;

    private string currencyField;

    private string originalProcessingDateField;

    private string refField;

    private string returnCodeField;

    private string returnDescriptionField;

    private string transCodeField;

    private decimal valueOfField;

    /// <remarks/>
    public PayerAccount PayerAccount
    {
      get
      {
        return this.payerAccountField;
      }
      set
      {
        this.payerAccountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string currency
    {
      get
      {
        return this.currencyField;
      }
      set
      {
        this.currencyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NMTOKEN" )]
    public string originalProcessingDate
    {
      get
      {
        return this.originalProcessingDateField;
      }
      set
      {
        this.originalProcessingDateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string @ref
    {
      get
      {
        return this.refField;
      }
      set
      {
        this.refField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NMTOKEN" )]
    public string returnCode
    {
      get
      {
        return this.returnCodeField;
      }
      set
      {
        this.returnCodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string returnDescription
    {
      get
      {
        return this.returnDescriptionField;
      }
      set
      {
        this.returnDescriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string transCode
    {
      get
      {
        return this.transCodeField;
      }
      set
      {
        this.transCodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal valueOf
    {
      get
      {
        return this.valueOfField;
      }
      set
      {
        this.valueOfField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class PayerAccount
  {
    private string bankNameField;

    private string branchNameField;

    private string nameField;

    private string numberField;

    private string refField;

    private string sortCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bankName
    {
      get
      {
        return this.bankNameField;
      }
      set
      {
        this.bankNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string branchName
    {
      get
      {
        return this.branchNameField;
      }
      set
      {
        this.branchNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string @ref
    {
      get
      {
        return this.refField;
      }
      set
      {
        this.refField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NMTOKEN" )]
    public string sortCode
    {
      get
      {
        return this.sortCodeField;
      }
      set
      {
        this.sortCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "4.0.30319.1" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "", IsNullable = false )]
  public partial class Totals
  {
    private string currencyField;

    private string numberOfField;

    private decimal valueOfField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "NCName" )]
    public string currency
    {
      get
      {
        return this.currencyField;
      }
      set
      {
        this.currencyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
    public string numberOf
    {
      get
      {
        return this.numberOfField;
      }
      set
      {
        this.numberOfField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal valueOf
    {
      get
      {
        return this.valueOfField;
      }
      set
      {
        this.valueOfField = value;
      }
    }
  }
}