/*This stub code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */

using System;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace WrapperTestWinforms
{
  internal partial class MainWindowController : BaseController<MainWindow>
  {
    partial void button1Click( EventArgs e )
    {
       textBox1.Text = "Hello, WORLD";
    }
  }
}

