/*Auto generated - this code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

//3rd Party
using RatCow.MvcFramework.WPF;

namespace WrapperTestWpf
{
  internal partial class MainWindowController
  {
    public MainWindowController() : base()
    {
    }

    partial void textBox1Click( RoutedEventArgs e );
    partial void textBox1TextChanged( RoutedEventArgs e );
    partial void button1Click(RoutedEventArgs e);
  }


#region GUI glue code

  partial class MainWindowController
  {
    [Outlet("textBox1")]
    public TextBox textBox1 { get; set; }
    [Action( "textBox1", "Click" )]
    public void FtextBox1_Click( object sender, RoutedEventArgs e )
    {
      //Auto generated call
      textBox1Click( e );
    }

    [Action( "textBox1", "TextChanged" )]
    public void FtextBox1_TextChanged( object sender, RoutedEventArgs e )
    {
      //Auto generated call
      textBox1TextChanged( e );
    }

    [Outlet("button1")]
    public Button button1 { get; set; }
    [Action("button1", "Click")]
    public void Fbutton1_Click(object sender, RoutedEventArgs e)
    {
      //Auto generated call
      button1Click(e);
    }

    //protected void SetData<T>(ListViewHelper<T> helper, List<T> data) where T : class
    //{
    //  //Auto generated call
    //  Type t = helper.GetType();
    //  t.InvokeMember("SetData", BindingFlags.Default | BindingFlags.InvokeMethod, null, helper, new object[] { data });
    //}

  }
#endregion /*GUI glue code*/

}

