/*This stub code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace $rootnamespace$
{
  internal partial class $fileinputname$Controller: BaseController<$fileinputname$>, IModalSubFormContainer
  {

  	//You must implement at least one of the following:
  	
  	#region IModalSubFormContainer Members

    public bool PerformModalTask()
    {
      throw new NotImplementedException();
    }

    public bool PerformModalTask<T>( T data )
    {
      throw new NotImplementedException();
    }

    public bool PerformModalTask<T, R>( T data, ref R result )
    {
      throw new NotImplementedException();
    }

    #endregion
  }
}

