/*This stub code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */

using System;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;
using RatCow.UKBankAccValidator;

namespace MVCApplication1
{
  internal partial class Form1Controller : BaseController<Form1>
  {
    partial void button1Click( EventArgs e )
    {
      if(Core.ValidateAccountNumber(Convert.ToInt32(textBox1.Text), Convert.ToInt32(textBox2.Text)) == ValidationResult.Valid)
        UIBridge.Alert("Valid");
      else
        UIBridge.Alert( "Invalid" );
    }
  }
}

