/*Auto generated - this code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace testapp3
{
	internal partial class Form1Controller
	{
		public Form1Controller() : base()
		{
		}

		partial void nullableDateTimePicker2Click(EventArgs e);
		partial void nullableDateTimePicker1Click(EventArgs e);
		partial void menuStrip1Click(EventArgs e);
		partial void aMenuToolStripMenuItemClick(EventArgs e);
		partial void aSubMenuToolStripMenuItemClick(EventArgs e);
		partial void aSubMenuItemToolStripMenuItemClick(EventArgs e);
		partial void aMenuItemToolStripMenuItemClick(EventArgs e);
		partial void listBox1Click(EventArgs e);
		partial void comboBox3Click(EventArgs e);
		partial void comboBox2Click(EventArgs e);
		partial void comboBox1Click(EventArgs e);
		partial void dateTimePicker1Click(EventArgs e);
		partial void checkBox1Click(EventArgs e);
		partial void checkBox1CheckedChanged(EventArgs e);
		partial void button1Click(EventArgs e);
		partial void label1Click(EventArgs e);
		partial void textBox1Click(EventArgs e);
		partial void textBox1TextChanged(EventArgs e);
	}


#region GUI glue code

	partial class Form1Controller
	{
		[Outlet("nullableDateTimePicker2")]
		public RatCow.MvcFramework.Mapping.Controls.NullableDateTimePicker nullableDateTimePicker2 { get; set; }
		[Action("nullableDateTimePicker2", "Click")]
		public void FnullableDateTimePicker2_Click(object sender, EventArgs e)
		{
			//Auto generated call
			nullableDateTimePicker2Click(e);
		}

		[Outlet("nullableDateTimePicker1")]
		public RatCow.MvcFramework.Mapping.Controls.NullableDateTimePicker nullableDateTimePicker1 { get; set; }
		[Action("nullableDateTimePicker1", "Click")]
		public void FnullableDateTimePicker1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			nullableDateTimePicker1Click(e);
		}

		[Outlet("menuStrip1")]
		public System.Windows.Forms.MenuStrip menuStrip1 { get; set; }
		[Action("menuStrip1", "Click")]
		public void FmenuStrip1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			menuStrip1Click(e);
		}

		[Outlet("aMenuToolStripMenuItem")]
		public System.Windows.Forms.ToolStripMenuItem aMenuToolStripMenuItem { get; set; }
		[Action("aMenuToolStripMenuItem", "Click")]
		public void FaMenuToolStripMenuItem_Click(object sender, EventArgs e)
		{
			//Auto generated call
			aMenuToolStripMenuItemClick(e);
		}

		[Outlet("aSubMenuToolStripMenuItem")]
		public System.Windows.Forms.ToolStripMenuItem aSubMenuToolStripMenuItem { get; set; }
		[Action("aSubMenuToolStripMenuItem", "Click")]
		public void FaSubMenuToolStripMenuItem_Click(object sender, EventArgs e)
		{
			//Auto generated call
			aSubMenuToolStripMenuItemClick(e);
		}

		[Outlet("aSubMenuItemToolStripMenuItem")]
		public System.Windows.Forms.ToolStripMenuItem aSubMenuItemToolStripMenuItem { get; set; }
		[Action("aSubMenuItemToolStripMenuItem", "Click")]
		public void FaSubMenuItemToolStripMenuItem_Click(object sender, EventArgs e)
		{
			//Auto generated call
			aSubMenuItemToolStripMenuItemClick(e);
		}

		[Outlet("aMenuItemToolStripMenuItem")]
		public System.Windows.Forms.ToolStripMenuItem aMenuItemToolStripMenuItem { get; set; }
		[Action("aMenuItemToolStripMenuItem", "Click")]
		public void FaMenuItemToolStripMenuItem_Click(object sender, EventArgs e)
		{
			//Auto generated call
			aMenuItemToolStripMenuItemClick(e);
		}

		[Outlet("listBox1")]
		public System.Windows.Forms.ListBox listBox1 { get; set; }
		[Action("listBox1", "Click")]
		public void FlistBox1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			listBox1Click(e);
		}

		[Outlet("comboBox3")]
		public System.Windows.Forms.ComboBox comboBox3 { get; set; }
		[Action("comboBox3", "Click")]
		public void FcomboBox3_Click(object sender, EventArgs e)
		{
			//Auto generated call
			comboBox3Click(e);
		}

		[Outlet("comboBox2")]
		public System.Windows.Forms.ComboBox comboBox2 { get; set; }
		[Action("comboBox2", "Click")]
		public void FcomboBox2_Click(object sender, EventArgs e)
		{
			//Auto generated call
			comboBox2Click(e);
		}

		[Outlet("comboBox1")]
		public System.Windows.Forms.ComboBox comboBox1 { get; set; }
		[Action("comboBox1", "Click")]
		public void FcomboBox1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			comboBox1Click(e);
		}

		[Outlet("dateTimePicker1")]
		public System.Windows.Forms.DateTimePicker dateTimePicker1 { get; set; }
		[Action("dateTimePicker1", "Click")]
		public void FdateTimePicker1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			dateTimePicker1Click(e);
		}

		[Outlet("checkBox1")]
		public System.Windows.Forms.CheckBox checkBox1 { get; set; }
		[Action("checkBox1", "Click")]
		public void FcheckBox1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			checkBox1Click(e);
		}

		[Action("checkBox1", "CheckedChanged")]
		public void FcheckBox1_CheckedChanged(object sender, EventArgs e)
		{
			//Auto generated call
			checkBox1CheckedChanged(e);
		}

		[Outlet("button1")]
		public System.Windows.Forms.Button button1 { get; set; }
		[Action("button1", "Click")]
		public void Fbutton1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			button1Click(e);
		}

		[Outlet("label1")]
		public System.Windows.Forms.Label label1 { get; set; }
		[Action("label1", "Click")]
		public void Flabel1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			label1Click(e);
		}

		[Outlet("textBox1")]
		public System.Windows.Forms.TextBox textBox1 { get; set; }
		[Action("textBox1", "Click")]
		public void FtextBox1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			textBox1Click(e);
		}

		[Action("textBox1", "TextChanged")]
		public void FtextBox1_TextChanged(object sender, EventArgs e)
		{
			//Auto generated call
			textBox1TextChanged(e);
		}

		[Outlet("imageList1")]
		public System.Windows.Forms.ImageList imageList1 { get; set; }
		protected void SetData<T>(ListViewHelper<T> helper, List<T> data) where T : class
		{
			//Auto generated call
			Type t = helper.GetType();
			t.InvokeMember("SetData", BindingFlags.Default | BindingFlags.InvokeMethod, null, helper, new object[] { data });
		}

	}
#endregion /*GUI glue code*/

}

