/*Auto generated - this code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace RatCow.MvcFramework.MvcMapTool
{
	internal partial class AddControlFormController
	{
		public AddControlFormController() : base()
		{
		}

		partial void controlComboClick(EventArgs e);
		partial void cancelButtonClick(EventArgs e);
		partial void okButtonClick(EventArgs e);
	}


#region GUI glue code

	partial class AddControlFormController
	{
		[Outlet("controlCombo")]
		public ComboBox controlCombo { get; set; }
		[Action("controlCombo", "Click")]
		public void FcontrolCombo_Click(object sender, EventArgs e)
		{
			//Auto generated call
			controlComboClick(e);
		}

		[Outlet("cancelButton")]
		public Button cancelButton { get; set; }
		[Action("cancelButton", "Click")]
		public void FcancelButton_Click(object sender, EventArgs e)
		{
			//Auto generated call
			cancelButtonClick(e);
		}

		[Outlet("okButton")]
		public Button okButton { get; set; }
		[Action("okButton", "Click")]
		public void FokButton_Click(object sender, EventArgs e)
		{
			//Auto generated call
			okButtonClick(e);
		}

		protected void SetData<T>(ListViewHelper<T> helper, List<T> data) where T : class
		{
			//Auto generated call
			Type t = helper.GetType();
			t.InvokeMember("SetData", BindingFlags.Default | BindingFlags.InvokeMethod, null, helper, new object[] { data });
		}

	}
#endregion /*GUI glue code*/

}

