/*Auto generated - this code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace RatCow.MvcFramework.MvcMapTool
{
	internal partial class AddGeneralItemFormController
	{
		public AddGeneralItemFormController() : base()
		{
		}

		partial void label2Click(EventArgs e);
		partial void label1Click(EventArgs e);
		partial void eventComboClick(EventArgs e);
		partial void eventComboSelectedIndexChanged(EventArgs e);
		partial void basedOnComboClick(EventArgs e);
		partial void basedOnComboSelectedIndexChanged(EventArgs e);
		partial void cancelButtonClick(EventArgs e);
		partial void okButtonClick(EventArgs e);
	}


#region GUI glue code

	partial class AddGeneralItemFormController
	{
		[Outlet("label2")]
		public Label label2 { get; set; }
		[Action("label2", "Click")]
		public void Flabel2_Click(object sender, EventArgs e)
		{
			//Auto generated call
			label2Click(e);
		}

		[Outlet("label1")]
		public Label label1 { get; set; }
		[Action("label1", "Click")]
		public void Flabel1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			label1Click(e);
		}

		[Outlet("eventCombo")]
		public ComboBox eventCombo { get; set; }
		[Action("eventCombo", "Click")]
		public void FeventCombo_Click(object sender, EventArgs e)
		{
			//Auto generated call
			eventComboClick(e);
		}

		[Action("eventCombo", "SelectedIndexChanged")]
		public void FeventCombo_SelectedIndexChanged(object sender, EventArgs e)
		{
			//Auto generated call
			eventComboSelectedIndexChanged(e);
		}

		[Outlet("basedOnCombo")]
		public ComboBox basedOnCombo { get; set; }
		[Action("basedOnCombo", "Click")]
		public void FbasedOnCombo_Click(object sender, EventArgs e)
		{
			//Auto generated call
			basedOnComboClick(e);
		}

		[Action("basedOnCombo", "SelectedIndexChanged")]
		public void FbasedOnCombo_SelectedIndexChanged(object sender, EventArgs e)
		{
			//Auto generated call
			basedOnComboSelectedIndexChanged(e);
		}

		[Outlet("cancelButton")]
		public Button cancelButton { get; set; }
		[Action("cancelButton", "Click")]
		public void FcancelButton_Click(object sender, EventArgs e)
		{
			//Auto generated call
			cancelButtonClick(e);
		}

		[Outlet("okButton")]
		public Button okButton { get; set; }
		[Action("okButton", "Click")]
		public void FokButton_Click(object sender, EventArgs e)
		{
			//Auto generated call
			okButtonClick(e);
		}

		protected void SetData<T>(ListViewHelper<T> helper, List<T> data) where T : class
		{
			//Auto generated call
			Type t = helper.GetType();
			t.InvokeMember("SetData", BindingFlags.Default | BindingFlags.InvokeMethod, null, helper, new object[] { data });
		}

	}
#endregion /*GUI glue code*/

}

