/*Auto generated - this code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */ 

using System; 
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

//3rd Party
using RatCow.MvcFramework;

namespace testapp3
{
	internal partial class Form1Controller: BaseController<Form1>
	{
		public Form1Controller() : base()
		{
		}

		partial void button1Click(EventArgs e);
		partial void label1Click(EventArgs e);
		partial void textBox1Click(EventArgs e);
		partial void textBox1TextChanged(EventArgs e);
	}


#region GUI glue code

	partial class Form1Controller
	{
		[Outlet("button1")]
		public Button button1 { get; set; }
		[Action("button1", "Click")]
		public void Fbutton1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			button1Click(e);
		}

		[Outlet("label1")]
		public Label label1 { get; set; }
		[Action("label1", "Click")]
		public void Flabel1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			label1Click(e);
		}

		[Outlet("textBox1")]
		public TextBox textBox1 { get; set; }
		[Action("textBox1", "Click")]
		public void FtextBox1_Click(object sender, EventArgs e)
		{
			//Auto generated call
			textBox1Click(e);
		}

		[Action("textBox1", "TextChanged")]
		public void FtextBox1_TextChanged(object sender, EventArgs e)
		{
			//Auto generated call
			textBox1TextChanged(e);
		}

		protected void SetData<T>(ListViewHelper<T> helper, List<T> data) where T : class
		{
			//Auto generated call
			Type t = helper.GetType();
			t.InvokeMember("SetData", BindingFlags.Default | BindingFlags.InvokeMethod, null, helper, new object[] { data });
		}

	}
#endregion /*GUI glue code*/

}

