/*This stub code was generated by the MvcFramework compiler, created by RatCow Soft - 
 See http://code.google.com/p/ratcowsoftopensource/ */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

//3rd Party
using RatCow.MvcFramework.WPF;

namespace WrapperTestWpf
{
  internal partial class MainWindowController : BaseController<MainWindow>
  {
    partial void button1Click( RoutedEventArgs e )
    {
       textBox1.Text = "Hello, WORLD";
    }
  }
}

